# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('robomaster', ['core', 'wifi'])
    module.source = [
        'model/vector2.cc',
        'model/robo-geometry.cc',
        'model/robo-ammo.cc',
        'model/robo-base.cc',
        'model/robo-hero.cc',
        'model/robo-shoot.cc',
        'model/robo-config-common.cc',

        'helper/robomaster-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('robomaster')
    module_test.source = [
        'test/robomaster-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'robomaster'
    headers.source = [
        'model/vector2.h',
        'model/robo-geometry.h',
        'model/robo-ammo.h',
        'model/robo-base.h',
        'model/robo-hero.h',
        'model/robo-shoot.h',
        'model/robo-config-common.h',
        
        'helper/robomaster-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

